<?php

namespace Proxies\__CG__\CCC\OfertasBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Facturas extends \CCC\OfertasBundle\Entity\Facturas implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setFecha($fecha)
    {
        $this->__load();
        return parent::setFecha($fecha);
    }

    public function getFecha()
    {
        $this->__load();
        return parent::getFecha();
    }

    public function setNo($no)
    {
        $this->__load();
        return parent::setNo($no);
    }

    public function getNo()
    {
        $this->__load();
        return parent::getNo();
    }

    public function setAnticipopc($anticipopc)
    {
        $this->__load();
        return parent::setAnticipopc($anticipopc);
    }

    public function getAnticipopc()
    {
        $this->__load();
        return parent::getAnticipopc();
    }

    public function setAnticipocupconsumido($anticipocupconsumido)
    {
        $this->__load();
        return parent::setAnticipocupconsumido($anticipocupconsumido);
    }

    public function getAnticipocupconsumido()
    {
        $this->__load();
        return parent::getAnticipocupconsumido();
    }

    public function setAnticipocucconsumido($anticipocucconsumido)
    {
        $this->__load();
        return parent::setAnticipocucconsumido($anticipocucconsumido);
    }

    public function getAnticipocucconsumido()
    {
        $this->__load();
        return parent::getAnticipocucconsumido();
    }

    public function addCertificacione(\CCC\OfertasBundle\Entity\CertFactura $certificaciones)
    {
        $this->__load();
        return parent::addCertificacione($certificaciones);
    }

    public function removeCertificacione(\CCC\OfertasBundle\Entity\CertFactura $certificaciones)
    {
        $this->__load();
        return parent::removeCertificacione($certificaciones);
    }

    public function getCertificaciones()
    {
        $this->__load();
        return parent::getCertificaciones();
    }

    public function addCertificacionesp(\CCC\OfertasBundle\Entity\CertFacturaP $certificacionesp)
    {
        $this->__load();
        return parent::addCertificacionesp($certificacionesp);
    }

    public function removeCertificacionesp(\CCC\OfertasBundle\Entity\CertFacturaP $certificacionesp)
    {
        $this->__load();
        return parent::removeCertificacionesp($certificacionesp);
    }

    public function getCertificacionesp()
    {
        $this->__load();
        return parent::getCertificacionesp();
    }

    public function setIdContrato(\CCC\OfertasBundle\Entity\Contratos $idContrato = NULL)
    {
        $this->__load();
        return parent::setIdContrato($idContrato);
    }

    public function getIdContrato()
    {
        $this->__load();
        return parent::getIdContrato();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'fecha', 'no', 'anticipopc', 'anticipocupconsumido', 'anticipocucconsumido', 'certificaciones', 'certificacionesp', 'idContrato');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}