<?php

namespace Proxies\__CG__\CCC\OfertasBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class PosibleCliente extends \CCC\OfertasBundle\Entity\PosibleCliente implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setCliente($cliente)
    {
        $this->__load();
        return parent::setCliente($cliente);
    }

    public function getCliente()
    {
        $this->__load();
        return parent::getCliente();
    }

    public function setEmpresa($empresa)
    {
        $this->__load();
        return parent::setEmpresa($empresa);
    }

    public function getEmpresa()
    {
        $this->__load();
        return parent::getEmpresa();
    }

    public function setSector($sector)
    {
        $this->__load();
        return parent::setSector($sector);
    }

    public function getSector()
    {
        $this->__load();
        return parent::getSector();
    }

    public function setDirecccion($direcccion)
    {
        $this->__load();
        return parent::setDirecccion($direcccion);
    }

    public function getDirecccion()
    {
        $this->__load();
        return parent::getDirecccion();
    }

    public function setNombreContacto($nombreContacto)
    {
        $this->__load();
        return parent::setNombreContacto($nombreContacto);
    }

    public function getNombreContacto()
    {
        $this->__load();
        return parent::getNombreContacto();
    }

    public function setTelefonoContacto($telefonoContacto)
    {
        $this->__load();
        return parent::setTelefonoContacto($telefonoContacto);
    }

    public function getTelefonoContacto()
    {
        $this->__load();
        return parent::getTelefonoContacto();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function addContacto(\CCC\OfertasBundle\Entity\ContactosPosibleCliente $contactos)
    {
        $this->__load();
        return parent::addContacto($contactos);
    }

    public function removeContacto(\CCC\OfertasBundle\Entity\ContactosPosibleCliente $contactos)
    {
        $this->__load();
        return parent::removeContacto($contactos);
    }

    public function getContactos()
    {
        $this->__load();
        return parent::getContactos();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'cliente', 'empresa', 'sector', 'direcccion', 'nombreContacto', 'telefonoContacto', 'email', 'contactos');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}