<?php

namespace Proxies\__CG__\CCC\OfertasBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class SolicitudOferta extends \CCC\OfertasBundle\Entity\SolicitudOferta implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setCodigo($codigo)
    {
        $this->__load();
        return parent::setCodigo($codigo);
    }

    public function getCodigo()
    {
        $this->__load();
        return parent::getCodigo();
    }

    public function setAnno($anno)
    {
        $this->__load();
        return parent::setAnno($anno);
    }

    public function getAnno()
    {
        $this->__load();
        return parent::getAnno();
    }

    public function setDescripcion($descripcion)
    {
        $this->__load();
        return parent::setDescripcion($descripcion);
    }

    public function getDescripcion()
    {
        $this->__load();
        return parent::getDescripcion();
    }

    public function setNombreObra($nombreObra)
    {
        $this->__load();
        return parent::setNombreObra($nombreObra);
    }

    public function getNombreObra()
    {
        $this->__load();
        return parent::getNombreObra();
    }

    public function setDireccionObra($direccionObra)
    {
        $this->__load();
        return parent::setDireccionObra($direccionObra);
    }

    public function getDireccionObra()
    {
        $this->__load();
        return parent::getDireccionObra();
    }

    public function setFechaLevantamiento($fechaLevantamiento)
    {
        $this->__load();
        return parent::setFechaLevantamiento($fechaLevantamiento);
    }

    public function getFechaLevantamiento()
    {
        $this->__load();
        return parent::getFechaLevantamiento();
    }

    public function setHoraLevantamiento($horaLevantamiento)
    {
        $this->__load();
        return parent::setHoraLevantamiento($horaLevantamiento);
    }

    public function getHoraLevantamiento()
    {
        $this->__load();
        return parent::getHoraLevantamiento();
    }

    public function setFechaCuantificacion($fechaCuantificacion)
    {
        $this->__load();
        return parent::setFechaCuantificacion($fechaCuantificacion);
    }

    public function getFechaCuantificacion()
    {
        $this->__load();
        return parent::getFechaCuantificacion();
    }

    public function setFechaCosteo($fechaCosteo)
    {
        $this->__load();
        return parent::setFechaCosteo($fechaCosteo);
    }

    public function getFechaCosteo()
    {
        $this->__load();
        return parent::getFechaCosteo();
    }

    public function setValorCosteo($valorCosteo)
    {
        $this->__load();
        return parent::setValorCosteo($valorCosteo);
    }

    public function getValorCosteo()
    {
        $this->__load();
        return parent::getValorCosteo();
    }

    public function setTipoMoneda($tipoMoneda)
    {
        $this->__load();
        return parent::setTipoMoneda($tipoMoneda);
    }

    public function getTipoMoneda()
    {
        $this->__load();
        return parent::getTipoMoneda();
    }

    public function setFechaElaboracionOferta($fechaElaboracionOferta)
    {
        $this->__load();
        return parent::setFechaElaboracionOferta($fechaElaboracionOferta);
    }

    public function getFechaElaboracionOferta()
    {
        $this->__load();
        return parent::getFechaElaboracionOferta();
    }

    public function setValorOfertaCUC($valorOfertaCUC)
    {
        $this->__load();
        return parent::setValorOfertaCUC($valorOfertaCUC);
    }

    public function getValorOfertaCUC()
    {
        $this->__load();
        return parent::getValorOfertaCUC();
    }

    public function setValorOfertaCUP($valorOfertaCUP)
    {
        $this->__load();
        return parent::setValorOfertaCUP($valorOfertaCUP);
    }

    public function getValorOfertaCUP()
    {
        $this->__load();
        return parent::getValorOfertaCUP();
    }

    public function setValorOfertaMaterialesCUC($valorOfertaMaterialesCUC)
    {
        $this->__load();
        return parent::setValorOfertaMaterialesCUC($valorOfertaMaterialesCUC);
    }

    public function getValorOfertaMaterialesCUC()
    {
        $this->__load();
        return parent::getValorOfertaMaterialesCUC();
    }

    public function setValorOfertaMaterialesCUP($valorOfertaMaterialesCUP)
    {
        $this->__load();
        return parent::setValorOfertaMaterialesCUP($valorOfertaMaterialesCUP);
    }

    public function getValorOfertaMaterialesCUP()
    {
        $this->__load();
        return parent::getValorOfertaMaterialesCUP();
    }

    public function setCantidadTrabajadores($cantidadTrabajadores)
    {
        $this->__load();
        return parent::setCantidadTrabajadores($cantidadTrabajadores);
    }

    public function getCantidadTrabajadores()
    {
        $this->__load();
        return parent::getCantidadTrabajadores();
    }

    public function setTiempoEjecucion($tiempoEjecucion)
    {
        $this->__load();
        return parent::setTiempoEjecucion($tiempoEjecucion);
    }

    public function getTiempoEjecucion()
    {
        $this->__load();
        return parent::getTiempoEjecucion();
    }

    public function setFechaEntregaCliente($fechaEntregaCliente)
    {
        $this->__load();
        return parent::setFechaEntregaCliente($fechaEntregaCliente);
    }

    public function getFechaEntregaCliente()
    {
        $this->__load();
        return parent::getFechaEntregaCliente();
    }

    public function setAprobado($aprobado)
    {
        $this->__load();
        return parent::setAprobado($aprobado);
    }

    public function getAprobado()
    {
        $this->__load();
        return parent::getAprobado();
    }

    public function setRechazado($rechazado)
    {
        $this->__load();
        return parent::setRechazado($rechazado);
    }

    public function getRechazado()
    {
        $this->__load();
        return parent::getRechazado();
    }

    public function setCausasRechazo($causasRechazo)
    {
        $this->__load();
        return parent::setCausasRechazo($causasRechazo);
    }

    public function getCausasRechazo()
    {
        $this->__load();
        return parent::getCausasRechazo();
    }

    public function setTieneCaratula($tieneCaratula)
    {
        $this->__load();
        return parent::setTieneCaratula($tieneCaratula);
    }

    public function getTieneCaratula()
    {
        $this->__load();
        return parent::getTieneCaratula();
    }

    public function setEsReoferta($esReoferta)
    {
        $this->__load();
        return parent::setEsReoferta($esReoferta);
    }

    public function getEsReoferta()
    {
        $this->__load();
        return parent::getEsReoferta();
    }

    public function setIdsolicitudoriginal($idsolicitudoriginal)
    {
        $this->__load();
        return parent::setIdsolicitudoriginal($idsolicitudoriginal);
    }

    public function getIdsolicitudoriginal()
    {
        $this->__load();
        return parent::getIdsolicitudoriginal();
    }

    public function setCantReofertas($cantReofertas)
    {
        $this->__load();
        return parent::setCantReofertas($cantReofertas);
    }

    public function getCantReofertas()
    {
        $this->__load();
        return parent::getCantReofertas();
    }

    public function setPorCientoAnticipo($porCientoAnticipo)
    {
        $this->__load();
        return parent::setPorCientoAnticipo($porCientoAnticipo);
    }

    public function getPorCientoAnticipo()
    {
        $this->__load();
        return parent::getPorCientoAnticipo();
    }

    public function setTerminado($terminado)
    {
        $this->__load();
        return parent::setTerminado($terminado);
    }

    public function getTerminado()
    {
        $this->__load();
        return parent::getTerminado();
    }

    public function setPrioridad($prioridad)
    {
        $this->__load();
        return parent::setPrioridad($prioridad);
    }

    public function getPrioridad()
    {
        $this->__load();
        return parent::getPrioridad();
    }

    public function setEsContrato($esContrato)
    {
        $this->__load();
        return parent::setEsContrato($esContrato);
    }

    public function getEsContrato()
    {
        $this->__load();
        return parent::getEsContrato();
    }

    public function setNoContrato($noContrato)
    {
        $this->__load();
        return parent::setNoContrato($noContrato);
    }

    public function getNoContrato()
    {
        $this->__load();
        return parent::getNoContrato();
    }

    public function setTipoContrato($tipoContrato)
    {
        $this->__load();
        return parent::setTipoContrato($tipoContrato);
    }

    public function getTipoContrato()
    {
        $this->__load();
        return parent::getTipoContrato();
    }

    public function setArchivado($archivado)
    {
        $this->__load();
        return parent::setArchivado($archivado);
    }

    public function getArchivado()
    {
        $this->__load();
        return parent::getArchivado();
    }

    public function setFechaFirmaClienteContrato($fechaFirmaClienteContrato)
    {
        $this->__load();
        return parent::setFechaFirmaClienteContrato($fechaFirmaClienteContrato);
    }

    public function getFechaFirmaClienteContrato()
    {
        $this->__load();
        return parent::getFechaFirmaClienteContrato();
    }

    public function setVigenciaContrato($vigenciaContrato)
    {
        $this->__load();
        return parent::setVigenciaContrato($vigenciaContrato);
    }

    public function getVigenciaContrato()
    {
        $this->__load();
        return parent::getVigenciaContrato();
    }

    public function setFechaVencimiento($fechaVencimiento)
    {
        $this->__load();
        return parent::setFechaVencimiento($fechaVencimiento);
    }

    public function getFechaVencimiento()
    {
        $this->__load();
        return parent::getFechaVencimiento();
    }

    public function setIdCliente(\CCC\OfertasBundle\Entity\Clientes $idCliente = NULL)
    {
        $this->__load();
        return parent::setIdCliente($idCliente);
    }

    public function getIdCliente()
    {
        $this->__load();
        return parent::getIdCliente();
    }

    public function addContrato(\CCC\OfertasBundle\Entity\Contrato $contratos)
    {
        $this->__load();
        return parent::addContrato($contratos);
    }

    public function removeContrato(\CCC\OfertasBundle\Entity\Contrato $contratos)
    {
        $this->__load();
        return parent::removeContrato($contratos);
    }

    public function getContratos()
    {
        $this->__load();
        return parent::getContratos();
    }

    public function addPresupuestoExcelComun(\CCC\OfertasBundle\Entity\PresupuestoExcelComun $presupuestoExcelComun)
    {
        $this->__load();
        return parent::addPresupuestoExcelComun($presupuestoExcelComun);
    }

    public function removePresupuestoExcelComun(\CCC\OfertasBundle\Entity\PresupuestoExcelComun $presupuestoExcelComun)
    {
        $this->__load();
        return parent::removePresupuestoExcelComun($presupuestoExcelComun);
    }

    public function getPresupuestoExcelComun()
    {
        $this->__load();
        return parent::getPresupuestoExcelComun();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'codigo', 'anno', 'descripcion', 'nombreObra', 'direccionObra', 'fechaLevantamiento', 'horaLevantamiento', 'fechaCuantificacion', 'fechaCosteo', 'valorCosteo', 'tipoMoneda', 'fechaElaboracionOferta', 'valorOfertaCUC', 'valorOfertaCUP', 'valorOfertaMaterialesCUC', 'valorOfertaMaterialesCUP', 'cantidadTrabajadores', 'tiempoEjecucion', 'fechaEntregaCliente', 'aprobado', 'rechazado', 'causasRechazo', 'tieneCaratula', 'esReoferta', 'idsolicitudoriginal', 'cantReofertas', 'porCientoAnticipo', 'terminado', 'prioridad', 'esContrato', 'noContrato', 'tipoContrato', 'archivado', 'fechaFirmaClienteContrato', 'vigenciaContrato', 'fechaVencimiento', 'idCliente', 'contratos', 'presupuestoExcelComun');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}