<?php

namespace Proxies\__CG__\CCC\OfertasBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Actividades extends \CCC\OfertasBundle\Entity\Actividades implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setCodigo($codigo)
    {
        $this->__load();
        return parent::setCodigo($codigo);
    }

    public function getCodigo()
    {
        $this->__load();
        return parent::getCodigo();
    }

    public function setActividad($actividad)
    {
        $this->__load();
        return parent::setActividad($actividad);
    }

    public function getActividad()
    {
        $this->__load();
        return parent::getActividad();
    }

    public function setUm($um)
    {
        $this->__load();
        return parent::setUm($um);
    }

    public function getUm()
    {
        $this->__load();
        return parent::getUm();
    }

    public function setCantidad($cantidad)
    {
        $this->__load();
        return parent::setCantidad($cantidad);
    }

    public function getCantidad()
    {
        $this->__load();
        return parent::getCantidad();
    }

    public function setPrecio($precio)
    {
        $this->__load();
        return parent::setPrecio($precio);
    }

    public function getPrecio()
    {
        $this->__load();
        return parent::getPrecio();
    }

    public function setTotal($total)
    {
        $this->__load();
        return parent::setTotal($total);
    }

    public function getTotal()
    {
        $this->__load();
        return parent::getTotal();
    }

    public function setCambioPlanificacion($cambioPlanificacion)
    {
        $this->__load();
        return parent::setCambioPlanificacion($cambioPlanificacion);
    }

    public function getCambioPlanificacion()
    {
        $this->__load();
        return parent::getCambioPlanificacion();
    }

    public function setIdGrupo(\CCC\OfertasBundle\Entity\GrupoActividadesObjetivo $idGrupo = NULL)
    {
        $this->__load();
        return parent::setIdGrupo($idGrupo);
    }

    public function getIdGrupo()
    {
        $this->__load();
        return parent::getIdGrupo();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'codigo', 'actividad', 'um', 'cantidad', 'precio', 'total', 'cambioPlanificacion', 'idGrupo');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}