<?php

namespace Proxies\__CG__\CCC\OfertasBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class GrupoActividadesObjetivo extends \CCC\OfertasBundle\Entity\GrupoActividadesObjetivo implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setCodigo($codigo)
    {
        $this->__load();
        return parent::setCodigo($codigo);
    }

    public function getCodigo()
    {
        $this->__load();
        return parent::getCodigo();
    }

    public function setGrupo($grupo)
    {
        $this->__load();
        return parent::setGrupo($grupo);
    }

    public function getGrupo()
    {
        $this->__load();
        return parent::getGrupo();
    }

    public function setIdObjetivo(\CCC\OfertasBundle\Entity\ObjetivosObra $idObjetivo = NULL)
    {
        $this->__load();
        return parent::setIdObjetivo($idObjetivo);
    }

    public function getIdObjetivo()
    {
        $this->__load();
        return parent::getIdObjetivo();
    }

    public function addActividade(\CCC\OfertasBundle\Entity\Actividades $actividades)
    {
        $this->__load();
        return parent::addActividade($actividades);
    }

    public function removeActividade(\CCC\OfertasBundle\Entity\Actividades $actividades)
    {
        $this->__load();
        return parent::removeActividade($actividades);
    }

    public function getActividades()
    {
        $this->__load();
        return parent::getActividades();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'codigo', 'grupo', 'idObjetivo', 'actividades');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}