<?php

namespace Proxies\__CG__\CCC\OfertasBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Contrato extends \CCC\OfertasBundle\Entity\Contrato implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setFechaEntrada($fechaEntrada)
    {
        $this->__load();
        return parent::setFechaEntrada($fechaEntrada);
    }

    public function getFechaEntrada()
    {
        $this->__load();
        return parent::getFechaEntrada();
    }

    public function setFechaSecretaria($fechaSecretaria)
    {
        $this->__load();
        return parent::setFechaSecretaria($fechaSecretaria);
    }

    public function getFechaSecretaria()
    {
        $this->__load();
        return parent::getFechaSecretaria();
    }

    public function setFechaEconomia($fechaEconomia)
    {
        $this->__load();
        return parent::setFechaEconomia($fechaEconomia);
    }

    public function getFechaEconomia()
    {
        $this->__load();
        return parent::getFechaEconomia();
    }

    public function setFechaNegocios($fechaNegocios)
    {
        $this->__load();
        return parent::setFechaNegocios($fechaNegocios);
    }

    public function getFechaNegocios()
    {
        $this->__load();
        return parent::getFechaNegocios();
    }

    public function setFechaEjecucion($fechaEjecucion)
    {
        $this->__load();
        return parent::setFechaEjecucion($fechaEjecucion);
    }

    public function getFechaEjecucion()
    {
        $this->__load();
        return parent::getFechaEjecucion();
    }

    public function setFechaEntregaCliente($fechaEntregaCliente)
    {
        $this->__load();
        return parent::setFechaEntregaCliente($fechaEntregaCliente);
    }

    public function getFechaEntregaCliente()
    {
        $this->__load();
        return parent::getFechaEntregaCliente();
    }

    public function setEstado($estado)
    {
        $this->__load();
        return parent::setEstado($estado);
    }

    public function getEstado()
    {
        $this->__load();
        return parent::getEstado();
    }

    public function setFechaFirmaCliente($fechaFirmaCliente)
    {
        $this->__load();
        return parent::setFechaFirmaCliente($fechaFirmaCliente);
    }

    public function getFechaFirmaCliente()
    {
        $this->__load();
        return parent::getFechaFirmaCliente();
    }

    public function setIdSolicitudOferta(\CCC\OfertasBundle\Entity\SolicitudOferta $idSolicitudOferta = NULL)
    {
        $this->__load();
        return parent::setIdSolicitudOferta($idSolicitudOferta);
    }

    public function getIdSolicitudOferta()
    {
        $this->__load();
        return parent::getIdSolicitudOferta();
    }

    public function setNotaEstado($notaEstado)
    {
        $this->__load();
        return parent::setNotaEstado($notaEstado);
    }

    public function getNotaEstado()
    {
        $this->__load();
        return parent::getNotaEstado();
    }

    public function setFechaFirmaFinal($fechaFirmaFinal)
    {
        $this->__load();
        return parent::setFechaFirmaFinal($fechaFirmaFinal);
    }

    public function getFechaFirmaFinal()
    {
        $this->__load();
        return parent::getFechaFirmaFinal();
    }

    public function setNoContrato($noContrato)
    {
        $this->__load();
        return parent::setNoContrato($noContrato);
    }

    public function getNoContrato()
    {
        $this->__load();
        return parent::getNoContrato();
    }

    public function setValorAnticipoCUP($valorAnticipoCUP)
    {
        $this->__load();
        return parent::setValorAnticipoCUP($valorAnticipoCUP);
    }

    public function getValorAnticipoCUP()
    {
        $this->__load();
        return parent::getValorAnticipoCUP();
    }

    public function setValorAnticipoCUC($valorAnticipoCUC)
    {
        $this->__load();
        return parent::setValorAnticipoCUC($valorAnticipoCUC);
    }

    public function getValorAnticipoCUC()
    {
        $this->__load();
        return parent::getValorAnticipoCUC();
    }

    public function setValorContratoCUP($valorContratoCUP)
    {
        $this->__load();
        return parent::setValorContratoCUP($valorContratoCUP);
    }

    public function getValorContratoCUP()
    {
        $this->__load();
        return parent::getValorContratoCUP();
    }

    public function setValorContratoCUC($valorContratoCUC)
    {
        $this->__load();
        return parent::setValorContratoCUC($valorContratoCUC);
    }

    public function getValorContratoCUC()
    {
        $this->__load();
        return parent::getValorContratoCUC();
    }

    public function setObjeto($objeto)
    {
        $this->__load();
        return parent::setObjeto($objeto);
    }

    public function getObjeto()
    {
        $this->__load();
        return parent::getObjeto();
    }

    public function setVigencia($vigencia)
    {
        $this->__load();
        return parent::setVigencia($vigencia);
    }

    public function getVigencia()
    {
        $this->__load();
        return parent::getVigencia();
    }

    public function setTipoTiempo($tipoTiempo)
    {
        $this->__load();
        return parent::setTipoTiempo($tipoTiempo);
    }

    public function getTipoTiempo()
    {
        $this->__load();
        return parent::getTipoTiempo();
    }

    public function setFechaActaInicio($fechaActaInicio)
    {
        $this->__load();
        return parent::setFechaActaInicio($fechaActaInicio);
    }

    public function getFechaActaInicio()
    {
        $this->__load();
        return parent::getFechaActaInicio();
    }

    public function setFechaActaEntrega($fechaActaEntrega)
    {
        $this->__load();
        return parent::setFechaActaEntrega($fechaActaEntrega);
    }

    public function getFechaActaEntrega()
    {
        $this->__load();
        return parent::getFechaActaEntrega();
    }

    public function setEsSuplemento($esSuplemento)
    {
        $this->__load();
        return parent::setEsSuplemento($esSuplemento);
    }

    public function getEsSuplemento()
    {
        $this->__load();
        return parent::getEsSuplemento();
    }

    public function setValorEjecutadoContratoCUP($valorEjecutadoContratoCUP)
    {
        $this->__load();
        return parent::setValorEjecutadoContratoCUP($valorEjecutadoContratoCUP);
    }

    public function getValorEjecutadoContratoCUP()
    {
        $this->__load();
        return parent::getValorEjecutadoContratoCUP();
    }

    public function setValorEjecutadoContratoCUC($valorEjecutadoContratoCUC)
    {
        $this->__load();
        return parent::setValorEjecutadoContratoCUC($valorEjecutadoContratoCUC);
    }

    public function getValorEjecutadoContratoCUC()
    {
        $this->__load();
        return parent::getValorEjecutadoContratoCUC();
    }

    public function setAnno($anno)
    {
        $this->__load();
        return parent::setAnno($anno);
    }

    public function getAnno()
    {
        $this->__load();
        return parent::getAnno();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'fechaEntrada', 'fechaSecretaria', 'fechaEconomia', 'fechaNegocios', 'fechaEjecucion', 'fechaEntregaCliente', 'estado', 'notaEstado', 'fechaFirmaCliente', 'fechaFirmaFinal', 'noContrato', 'objeto', 'valorAnticipoCUP', 'valorAnticipoCUC', 'valorContratoCUP', 'valorContratoCUC', 'valorEjecutadoContratoCUP', 'valorEjecutadoContratoCUC', 'vigencia', 'tipoTiempo', 'fechaActaInicio', 'fechaActaEntrega', 'esSuplemento', 'anno', 'idSolicitudOferta');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}