<?php

namespace Proxies\__CG__\CCC\OfertasBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class PresupuestoExcelComun extends \CCC\OfertasBundle\Entity\PresupuestoExcelComun implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setResumenpresupuestocup($resumenpresupuestocup)
    {
        $this->__load();
        return parent::setResumenpresupuestocup($resumenpresupuestocup);
    }

    public function getResumenpresupuestocup()
    {
        $this->__load();
        return parent::getResumenpresupuestocup();
    }

    public function setResumenpresupuestocuc($resumenpresupuestocuc)
    {
        $this->__load();
        return parent::setResumenpresupuestocuc($resumenpresupuestocuc);
    }

    public function getResumenpresupuestocuc()
    {
        $this->__load();
        return parent::getResumenpresupuestocuc();
    }

    public function setGastosdirectoscup($gastosdirectoscup)
    {
        $this->__load();
        return parent::setGastosdirectoscup($gastosdirectoscup);
    }

    public function getGastosdirectoscup()
    {
        $this->__load();
        return parent::getGastosdirectoscup();
    }

    public function setGastosdirectoscuc($gastosdirectoscuc)
    {
        $this->__load();
        return parent::setGastosdirectoscuc($gastosdirectoscuc);
    }

    public function getGastosdirectoscuc()
    {
        $this->__load();
        return parent::getGastosdirectoscuc();
    }

    public function setGastosgeneralescup($gastosgeneralescup)
    {
        $this->__load();
        return parent::setGastosgeneralescup($gastosgeneralescup);
    }

    public function getGastosgeneralescup()
    {
        $this->__load();
        return parent::getGastosgeneralescup();
    }

    public function setGastosgeneralescuc($gastosgeneralescuc)
    {
        $this->__load();
        return parent::setGastosgeneralescuc($gastosgeneralescuc);
    }

    public function getGastosgeneralescuc()
    {
        $this->__load();
        return parent::getGastosgeneralescuc();
    }

    public function setGastosindirectoscup($gastosindirectoscup)
    {
        $this->__load();
        return parent::setGastosindirectoscup($gastosindirectoscup);
    }

    public function getGastosindirectoscup()
    {
        $this->__load();
        return parent::getGastosindirectoscup();
    }

    public function setGastosindirectoscuc($gastosindirectoscuc)
    {
        $this->__load();
        return parent::setGastosindirectoscuc($gastosindirectoscuc);
    }

    public function getGastosindirectoscuc()
    {
        $this->__load();
        return parent::getGastosindirectoscuc();
    }

    public function setPresupuestosindependientescup($presupuestosindependientescup)
    {
        $this->__load();
        return parent::setPresupuestosindependientescup($presupuestosindependientescup);
    }

    public function getPresupuestosindependientescup()
    {
        $this->__load();
        return parent::getPresupuestosindependientescup();
    }

    public function setPresupuestosindependientescuc($presupuestosindependientescuc)
    {
        $this->__load();
        return parent::setPresupuestosindependientescuc($presupuestosindependientescuc);
    }

    public function getPresupuestosindependientescuc()
    {
        $this->__load();
        return parent::getPresupuestosindependientescuc();
    }

    public function setImprevistoscup($imprevistoscup)
    {
        $this->__load();
        return parent::setImprevistoscup($imprevistoscup);
    }

    public function getImprevistoscup()
    {
        $this->__load();
        return parent::getImprevistoscup();
    }

    public function setImprevistoscuc($imprevistoscuc)
    {
        $this->__load();
        return parent::setImprevistoscuc($imprevistoscuc);
    }

    public function getImprevistoscuc()
    {
        $this->__load();
        return parent::getImprevistoscuc();
    }

    public function setCostototalcup($costototalcup)
    {
        $this->__load();
        return parent::setCostototalcup($costototalcup);
    }

    public function getCostototalcup()
    {
        $this->__load();
        return parent::getCostototalcup();
    }

    public function setCostototalcuc($costototalcuc)
    {
        $this->__load();
        return parent::setCostototalcuc($costototalcuc);
    }

    public function getCostototalcuc()
    {
        $this->__load();
        return parent::getCostototalcuc();
    }

    public function setPcutilidad($pcutilidad)
    {
        $this->__load();
        return parent::setPcutilidad($pcutilidad);
    }

    public function getPcutilidad()
    {
        $this->__load();
        return parent::getPcutilidad();
    }

    public function setUtilidadcup($utilidadcup)
    {
        $this->__load();
        return parent::setUtilidadcup($utilidadcup);
    }

    public function getUtilidadcup()
    {
        $this->__load();
        return parent::getUtilidadcup();
    }

    public function setUtilidadcuc($utilidadcuc)
    {
        $this->__load();
        return parent::setUtilidadcuc($utilidadcuc);
    }

    public function getUtilidadcuc()
    {
        $this->__load();
        return parent::getUtilidadcuc();
    }

    public function setPrecioservconstcup($precioservconstcup)
    {
        $this->__load();
        return parent::setPrecioservconstcup($precioservconstcup);
    }

    public function getPrecioservconstcup()
    {
        $this->__load();
        return parent::getPrecioservconstcup();
    }

    public function setPrecioservconstcuc($precioservconstcuc)
    {
        $this->__load();
        return parent::setPrecioservconstcuc($precioservconstcuc);
    }

    public function getPrecioservconstcuc()
    {
        $this->__load();
        return parent::getPrecioservconstcuc();
    }

    public function setPagotributoscup($pagotributoscup)
    {
        $this->__load();
        return parent::setPagotributoscup($pagotributoscup);
    }

    public function getPagotributoscup()
    {
        $this->__load();
        return parent::getPagotributoscup();
    }

    public function setPagotributoscuc($pagotributoscuc)
    {
        $this->__load();
        return parent::setPagotributoscuc($pagotributoscuc);
    }

    public function getPagotributoscuc()
    {
        $this->__load();
        return parent::getPagotributoscuc();
    }

    public function setPreciomanoobracup($preciomanoobracup)
    {
        $this->__load();
        return parent::setPreciomanoobracup($preciomanoobracup);
    }

    public function getPreciomanoobracup()
    {
        $this->__load();
        return parent::getPreciomanoobracup();
    }

    public function setPreciomanoobracuc($preciomanoobracuc)
    {
        $this->__load();
        return parent::setPreciomanoobracuc($preciomanoobracuc);
    }

    public function getPreciomanoobracuc()
    {
        $this->__load();
        return parent::getPreciomanoobracuc();
    }

    public function setPreciomaterialescup($preciomaterialescup)
    {
        $this->__load();
        return parent::setPreciomaterialescup($preciomaterialescup);
    }

    public function getPreciomaterialescup()
    {
        $this->__load();
        return parent::getPreciomaterialescup();
    }

    public function setPreciomaterialescuc($preciomaterialescuc)
    {
        $this->__load();
        return parent::setPreciomaterialescuc($preciomaterialescuc);
    }

    public function getPreciomaterialescuc()
    {
        $this->__load();
        return parent::getPreciomaterialescuc();
    }

    public function setPreciototalcup($preciototalcup)
    {
        $this->__load();
        return parent::setPreciototalcup($preciototalcup);
    }

    public function getPreciototalcup()
    {
        $this->__load();
        return parent::getPreciototalcup();
    }

    public function setPreciototalcuc($preciototalcuc)
    {
        $this->__load();
        return parent::setPreciototalcuc($preciototalcuc);
    }

    public function getPreciototalcuc()
    {
        $this->__load();
        return parent::getPreciototalcuc();
    }

    public function setTiempoejecuciondias($tiempoejecuciondias)
    {
        $this->__load();
        return parent::setTiempoejecuciondias($tiempoejecuciondias);
    }

    public function getTiempoejecuciondias()
    {
        $this->__load();
        return parent::getTiempoejecuciondias();
    }

    public function setCanthombres($canthombres)
    {
        $this->__load();
        return parent::setCanthombres($canthombres);
    }

    public function getCanthombres()
    {
        $this->__load();
        return parent::getCanthombres();
    }

    public function setIdSolicitudOferta(\CCC\OfertasBundle\Entity\SolicitudOferta $idSolicitudOferta = NULL)
    {
        $this->__load();
        return parent::setIdSolicitudOferta($idSolicitudOferta);
    }

    public function getIdSolicitudOferta()
    {
        $this->__load();
        return parent::getIdSolicitudOferta();
    }

    public function addObjetivo(\CCC\OfertasBundle\Entity\ObjetivosObra $objetivos)
    {
        $this->__load();
        return parent::addObjetivo($objetivos);
    }

    public function removeObjetivo(\CCC\OfertasBundle\Entity\ObjetivosObra $objetivos)
    {
        $this->__load();
        return parent::removeObjetivo($objetivos);
    }

    public function getObjetivos()
    {
        $this->__load();
        return parent::getObjetivos();
    }

    public function addMateriale(\CCC\OfertasBundle\Entity\MaterialesPresExcelComun $materiales)
    {
        $this->__load();
        return parent::addMateriale($materiales);
    }

    public function removeMateriale(\CCC\OfertasBundle\Entity\MaterialesPresExcelComun $materiales)
    {
        $this->__load();
        return parent::removeMateriale($materiales);
    }

    public function getMateriales()
    {
        $this->__load();
        return parent::getMateriales();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'resumenpresupuestocup', 'resumenpresupuestocuc', 'gastosdirectoscup', 'gastosdirectoscuc', 'gastosgeneralescup', 'gastosgeneralescuc', 'gastosindirectoscup', 'gastosindirectoscuc', 'presupuestosindependientescup', 'presupuestosindependientescuc', 'imprevistoscup', 'imprevistoscuc', 'costototalcup', 'costototalcuc', 'pcutilidad', 'utilidadcup', 'utilidadcuc', 'precioservconstcup', 'precioservconstcuc', 'pagotributoscup', 'pagotributoscuc', 'preciomanoobracup', 'preciomanoobracuc', 'preciomaterialescup', 'preciomaterialescuc', 'preciototalcup', 'preciototalcuc', 'tiempoejecuciondias', 'canthombres', 'idSolicitudOferta', 'objetivos', 'materiales');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}