<?php

namespace Proxies\__CG__\CCC\OfertasBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Clientes extends \CCC\OfertasBundle\Entity\Clientes implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setCodigo($codigo)
    {
        $this->__load();
        return parent::setCodigo($codigo);
    }

    public function getCodigo()
    {
        $this->__load();
        return parent::getCodigo();
    }

    public function setCliente($cliente)
    {
        $this->__load();
        return parent::setCliente($cliente);
    }

    public function getCliente()
    {
        $this->__load();
        return parent::getCliente();
    }

    public function setEmpresa($empresa)
    {
        $this->__load();
        return parent::setEmpresa($empresa);
    }

    public function getEmpresa()
    {
        $this->__load();
        return parent::getEmpresa();
    }

    public function setSector($sector)
    {
        $this->__load();
        return parent::setSector($sector);
    }

    public function getSector()
    {
        $this->__load();
        return parent::getSector();
    }

    public function setDireccion($direccion)
    {
        $this->__load();
        return parent::setDireccion($direccion);
    }

    public function getDireccion()
    {
        $this->__load();
        return parent::getDireccion();
    }

    public function setNombreContacto($nombreContacto)
    {
        $this->__load();
        return parent::setNombreContacto($nombreContacto);
    }

    public function getNombreContacto()
    {
        $this->__load();
        return parent::getNombreContacto();
    }

    public function setDireccionObra($direccionObra)
    {
        $this->__load();
        return parent::setDireccionObra($direccionObra);
    }

    public function getDireccionObra()
    {
        $this->__load();
        return parent::getDireccionObra();
    }

    public function setTelefonoContacto($telefonoContacto)
    {
        $this->__load();
        return parent::setTelefonoContacto($telefonoContacto);
    }

    public function getTelefonoContacto()
    {
        $this->__load();
        return parent::getTelefonoContacto();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setNombreempresa($nombreempresa)
    {
        $this->__load();
        return parent::setNombreempresa($nombreempresa);
    }

    public function getNombreempresa()
    {
        $this->__load();
        return parent::getNombreempresa();
    }

    public function setNoresolucion($noresolucion)
    {
        $this->__load();
        return parent::setNoresolucion($noresolucion);
    }

    public function getNoresolucion()
    {
        $this->__load();
        return parent::getNoresolucion();
    }

    public function setFecharesolucion($fecharesolucion)
    {
        $this->__load();
        return parent::setFecharesolucion($fecharesolucion);
    }

    public function getFecharesolucion()
    {
        $this->__load();
        return parent::getFecharesolucion();
    }

    public function setOrganismoemite($organismoemite)
    {
        $this->__load();
        return parent::setOrganismoemite($organismoemite);
    }

    public function getOrganismoemite()
    {
        $this->__load();
        return parent::getOrganismoemite();
    }

    public function setNombreresolucion($nombreresolucion)
    {
        $this->__load();
        return parent::setNombreresolucion($nombreresolucion);
    }

    public function getNombreresolucion()
    {
        $this->__load();
        return parent::getNombreresolucion();
    }

    public function setDireccionresolucion($direccionresolucion)
    {
        $this->__load();
        return parent::setDireccionresolucion($direccionresolucion);
    }

    public function getDireccionresolucion()
    {
        $this->__load();
        return parent::getDireccionresolucion();
    }

    public function setReeup($reeup)
    {
        $this->__load();
        return parent::setReeup($reeup);
    }

    public function getReeup()
    {
        $this->__load();
        return parent::getReeup();
    }

    public function setNoidentributaria($noidentributaria)
    {
        $this->__load();
        return parent::setNoidentributaria($noidentributaria);
    }

    public function getNoidentributaria()
    {
        $this->__load();
        return parent::getNoidentributaria();
    }

    public function setCuentacuc($cuentacuc)
    {
        $this->__load();
        return parent::setCuentacuc($cuentacuc);
    }

    public function getCuentacuc()
    {
        $this->__load();
        return parent::getCuentacuc();
    }

    public function setTitularcuentacuc($titularcuentacuc)
    {
        $this->__load();
        return parent::setTitularcuentacuc($titularcuentacuc);
    }

    public function getTitularcuentacuc()
    {
        $this->__load();
        return parent::getTitularcuentacuc();
    }

    public function setBancocuentacuc($bancocuentacuc)
    {
        $this->__load();
        return parent::setBancocuentacuc($bancocuentacuc);
    }

    public function getBancocuentacuc()
    {
        $this->__load();
        return parent::getBancocuentacuc();
    }

    public function setSucursalcuentacuc($sucursalcuentacuc)
    {
        $this->__load();
        return parent::setSucursalcuentacuc($sucursalcuentacuc);
    }

    public function getSucursalcuentacuc()
    {
        $this->__load();
        return parent::getSucursalcuentacuc();
    }

    public function setDireccioncuentacuc($direccioncuentacuc)
    {
        $this->__load();
        return parent::setDireccioncuentacuc($direccioncuentacuc);
    }

    public function getDireccioncuentacuc()
    {
        $this->__load();
        return parent::getDireccioncuentacuc();
    }

    public function setCuentacup($cuentacup)
    {
        $this->__load();
        return parent::setCuentacup($cuentacup);
    }

    public function getCuentacup()
    {
        $this->__load();
        return parent::getCuentacup();
    }

    public function setTitularcuentacup($titularcuentacup)
    {
        $this->__load();
        return parent::setTitularcuentacup($titularcuentacup);
    }

    public function getTitularcuentacup()
    {
        $this->__load();
        return parent::getTitularcuentacup();
    }

    public function setBancocuentacup($bancocuentacup)
    {
        $this->__load();
        return parent::setBancocuentacup($bancocuentacup);
    }

    public function getBancocuentacup()
    {
        $this->__load();
        return parent::getBancocuentacup();
    }

    public function setSucursalcuentacup($sucursalcuentacup)
    {
        $this->__load();
        return parent::setSucursalcuentacup($sucursalcuentacup);
    }

    public function getSucursalcuentacup()
    {
        $this->__load();
        return parent::getSucursalcuentacup();
    }

    public function setDireccioncuentacup($direccioncuentacup)
    {
        $this->__load();
        return parent::setDireccioncuentacup($direccioncuentacup);
    }

    public function getDireccioncuentacup()
    {
        $this->__load();
        return parent::getDireccioncuentacup();
    }

    public function setNolicencia($nolicencia)
    {
        $this->__load();
        return parent::setNolicencia($nolicencia);
    }

    public function getNolicencia()
    {
        $this->__load();
        return parent::getNolicencia();
    }

    public function setNoregistro($noregistro)
    {
        $this->__load();
        return parent::setNoregistro($noregistro);
    }

    public function getNoregistro()
    {
        $this->__load();
        return parent::getNoregistro();
    }

    public function setReplicencia($replicencia)
    {
        $this->__load();
        return parent::setReplicencia($replicencia);
    }

    public function getReplicencia()
    {
        $this->__load();
        return parent::getReplicencia();
    }

    public function setCargoreplicencia($cargoreplicencia)
    {
        $this->__load();
        return parent::setCargoreplicencia($cargoreplicencia);
    }

    public function getCargoreplicencia()
    {
        $this->__load();
        return parent::getCargoreplicencia();
    }

    public function setNoresolrep($noresolrep)
    {
        $this->__load();
        return parent::setNoresolrep($noresolrep);
    }

    public function getNoresolrep()
    {
        $this->__load();
        return parent::getNoresolrep();
    }

    public function setFecharesrep($fecharesrep)
    {
        $this->__load();
        return parent::setFecharesrep($fecharesrep);
    }

    public function getFecharesrep()
    {
        $this->__load();
        return parent::getFecharesrep();
    }

    public function setEmitidaresolrep($emitidaresolrep)
    {
        $this->__load();
        return parent::setEmitidaresolrep($emitidaresolrep);
    }

    public function getEmitidaresolrep()
    {
        $this->__load();
        return parent::getEmitidaresolrep();
    }

    public function addSolicitudesOferta(\CCC\OfertasBundle\Entity\SolicitudOferta $solicitudesOferta)
    {
        $this->__load();
        return parent::addSolicitudesOferta($solicitudesOferta);
    }

    public function removeSolicitudesOferta(\CCC\OfertasBundle\Entity\SolicitudOferta $solicitudesOferta)
    {
        $this->__load();
        return parent::removeSolicitudesOferta($solicitudesOferta);
    }

    public function getSolicitudesOferta()
    {
        $this->__load();
        return parent::getSolicitudesOferta();
    }

    public function addContacto(\CCC\OfertasBundle\Entity\Contactos $contactos)
    {
        $this->__load();
        return parent::addContacto($contactos);
    }

    public function removeContacto(\CCC\OfertasBundle\Entity\Contactos $contactos)
    {
        $this->__load();
        return parent::removeContacto($contactos);
    }

    public function getContactos()
    {
        $this->__load();
        return parent::getContactos();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'codigo', 'cliente', 'empresa', 'sector', 'direccion', 'nombreContacto', 'direccionObra', 'telefonoContacto', 'email', 'nombreempresa', 'noresolucion', 'fecharesolucion', 'organismoemite', 'nombreresolucion', 'direccionresolucion', 'reeup', 'noidentributaria', 'cuentacuc', 'titularcuentacuc', 'bancocuentacuc', 'sucursalcuentacuc', 'direccioncuentacuc', 'cuentacup', 'titularcuentacup', 'bancocuentacup', 'sucursalcuentacup', 'direccioncuentacup', 'nolicencia', 'noregistro', 'replicencia', 'cargoreplicencia', 'noresolrep', 'fecharesrep', 'emitidaresolrep', 'solicitudesOferta', 'contactos');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}