<?php

namespace Proxies\__CG__\CCC\OfertasBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ContratoN extends \CCC\OfertasBundle\Entity\ContratoN implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNoContrato($noContrato)
    {
        $this->__load();
        return parent::setNoContrato($noContrato);
    }

    public function getNoContrato()
    {
        $this->__load();
        return parent::getNoContrato();
    }

    public function setAnno($anno)
    {
        $this->__load();
        return parent::setAnno($anno);
    }

    public function getAnno()
    {
        $this->__load();
        return parent::getAnno();
    }

    public function setTipocontrato($tipocontrato)
    {
        $this->__load();
        return parent::setTipocontrato($tipocontrato);
    }

    public function getTipocontrato()
    {
        $this->__load();
        return parent::getTipocontrato();
    }

    public function setVigencia($vigencia)
    {
        $this->__load();
        return parent::setVigencia($vigencia);
    }

    public function getVigencia()
    {
        $this->__load();
        return parent::getVigencia();
    }

    public function setValorCUC($valorCUC)
    {
        $this->__load();
        return parent::setValorCUC($valorCUC);
    }

    public function getValorCUC()
    {
        $this->__load();
        return parent::getValorCUC();
    }

    public function setValorCUP($valorCUP)
    {
        $this->__load();
        return parent::setValorCUP($valorCUP);
    }

    public function getValorCUP()
    {
        $this->__load();
        return parent::getValorCUP();
    }

    public function setIdOferta($idOferta)
    {
        $this->__load();
        return parent::setIdOferta($idOferta);
    }

    public function getIdOferta()
    {
        $this->__load();
        return parent::getIdOferta();
    }

    public function setEsSuplemento($esSuplemento)
    {
        $this->__load();
        return parent::setEsSuplemento($esSuplemento);
    }

    public function getEsSuplemento()
    {
        $this->__load();
        return parent::getEsSuplemento();
    }

    public function setIdContratoDependiente($idContratoDependiente)
    {
        $this->__load();
        return parent::setIdContratoDependiente($idContratoDependiente);
    }

    public function getIdContratoDependiente()
    {
        $this->__load();
        return parent::getIdContratoDependiente();
    }

    public function addIdcliente(\CCC\OfertasBundle\Entity\ClientesContratoN $idclientes)
    {
        $this->__load();
        return parent::addIdcliente($idclientes);
    }

    public function removeIdcliente(\CCC\OfertasBundle\Entity\ClientesContratoN $idclientes)
    {
        $this->__load();
        return parent::removeIdcliente($idclientes);
    }

    public function getIdclientes()
    {
        $this->__load();
        return parent::getIdclientes();
    }

    public function setFechaFirmaCliente($fechaFirmaCliente)
    {
        $this->__load();
        return parent::setFechaFirmaCliente($fechaFirmaCliente);
    }

    public function getFechaFirmaCliente()
    {
        $this->__load();
        return parent::getFechaFirmaCliente();
    }

    public function setTipoSuplemento($tipoSuplemento)
    {
        $this->__load();
        return parent::setTipoSuplemento($tipoSuplemento);
    }

    public function getTipoSuplemento()
    {
        $this->__load();
        return parent::getTipoSuplemento();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'noContrato', 'anno', 'tipocontrato', 'vigencia', 'valorCUC', 'valorCUP', 'idOferta', 'esSuplemento', 'tipoSuplemento', 'idContratoDependiente', 'fechaFirmaCliente', 'idclientes');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}