<?php

namespace Proxies\__CG__\CCC\OfertasBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class ObjetivosObra extends \CCC\OfertasBundle\Entity\ObjetivosObra implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setCodigo($codigo)
    {
        $this->__load();
        return parent::setCodigo($codigo);
    }

    public function getCodigo()
    {
        $this->__load();
        return parent::getCodigo();
    }

    public function setObjetivo($objetivo)
    {
        $this->__load();
        return parent::setObjetivo($objetivo);
    }

    public function getObjetivo()
    {
        $this->__load();
        return parent::getObjetivo();
    }

    public function setDescripcion($descripcion)
    {
        $this->__load();
        return parent::setDescripcion($descripcion);
    }

    public function getDescripcion()
    {
        $this->__load();
        return parent::getDescripcion();
    }

    public function setEsSuplemento($esSuplemento)
    {
        $this->__load();
        return parent::setEsSuplemento($esSuplemento);
    }

    public function getEsSuplemento()
    {
        $this->__load();
        return parent::getEsSuplemento();
    }

    public function setNoSuplemento($noSuplemento)
    {
        $this->__load();
        return parent::setNoSuplemento($noSuplemento);
    }

    public function getNoSuplemento()
    {
        $this->__load();
        return parent::getNoSuplemento();
    }

    public function setIdPresupuesto(\CCC\OfertasBundle\Entity\PresupuestoExcelComun $idPresupuesto = NULL)
    {
        $this->__load();
        return parent::setIdPresupuesto($idPresupuesto);
    }

    public function getIdPresupuesto()
    {
        $this->__load();
        return parent::getIdPresupuesto();
    }

    public function addGruposActividade(\CCC\OfertasBundle\Entity\GrupoActividadesObjetivo $gruposActividades)
    {
        $this->__load();
        return parent::addGruposActividade($gruposActividades);
    }

    public function removeGruposActividade(\CCC\OfertasBundle\Entity\GrupoActividadesObjetivo $gruposActividades)
    {
        $this->__load();
        return parent::removeGruposActividade($gruposActividades);
    }

    public function getGruposActividades()
    {
        $this->__load();
        return parent::getGruposActividades();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'codigo', 'objetivo', 'descripcion', 'esSuplemento', 'noSuplemento', 'idPresupuesto', 'gruposActividades');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}