<?php

namespace Proxies\__CG__\CCC\OfertasBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class CertificacionExcel extends \CCC\OfertasBundle\Entity\CertificacionExcel implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setFacturado($facturado)
    {
        $this->__load();
        return parent::setFacturado($facturado);
    }

    public function getFacturado()
    {
        $this->__load();
        return parent::getFacturado();
    }

    public function setObjeto($objeto)
    {
        $this->__load();
        return parent::setObjeto($objeto);
    }

    public function getObjeto()
    {
        $this->__load();
        return parent::getObjeto();
    }

    public function setDesde($desde)
    {
        $this->__load();
        return parent::setDesde($desde);
    }

    public function getDesde()
    {
        $this->__load();
        return parent::getDesde();
    }

    public function setHasta($hasta)
    {
        $this->__load();
        return parent::setHasta($hasta);
    }

    public function getHasta()
    {
        $this->__load();
        return parent::getHasta();
    }

    public function setGastoResuemenPresupuestoCUPExcel($gastoResuemenPresupuestoCUPExcel)
    {
        $this->__load();
        return parent::setGastoResuemenPresupuestoCUPExcel($gastoResuemenPresupuestoCUPExcel);
    }

    public function getGastoResuemenPresupuestoCUPExcel()
    {
        $this->__load();
        return parent::getGastoResuemenPresupuestoCUPExcel();
    }

    public function setGastoResuemenPresupuestoCUCExcel($gastoResuemenPresupuestoCUCExcel)
    {
        $this->__load();
        return parent::setGastoResuemenPresupuestoCUCExcel($gastoResuemenPresupuestoCUCExcel);
    }

    public function getGastoResuemenPresupuestoCUCExcel()
    {
        $this->__load();
        return parent::getGastoResuemenPresupuestoCUCExcel();
    }

    public function setGastoDirectoCUPExcel($gastoDirectoCUPExcel)
    {
        $this->__load();
        return parent::setGastoDirectoCUPExcel($gastoDirectoCUPExcel);
    }

    public function getGastoDirectoCUPExcel()
    {
        $this->__load();
        return parent::getGastoDirectoCUPExcel();
    }

    public function setGastoDirectoCUCExcel($gastoDirectoCUCExcel)
    {
        $this->__load();
        return parent::setGastoDirectoCUCExcel($gastoDirectoCUCExcel);
    }

    public function getGastoDirectoCUCExcel()
    {
        $this->__load();
        return parent::getGastoDirectoCUCExcel();
    }

    public function setGastoGeneralCUPExcel($gastoGeneralCUPExcel)
    {
        $this->__load();
        return parent::setGastoGeneralCUPExcel($gastoGeneralCUPExcel);
    }

    public function getGastoGeneralCUPExcel()
    {
        $this->__load();
        return parent::getGastoGeneralCUPExcel();
    }

    public function setGastoGeneralCUCExcel($gastoGeneralCUCExcel)
    {
        $this->__load();
        return parent::setGastoGeneralCUCExcel($gastoGeneralCUCExcel);
    }

    public function getGastoGeneralCUCExcel()
    {
        $this->__load();
        return parent::getGastoGeneralCUCExcel();
    }

    public function setGastoIndirectoCUPExcel($gastoIndirectoCUPExcel)
    {
        $this->__load();
        return parent::setGastoIndirectoCUPExcel($gastoIndirectoCUPExcel);
    }

    public function getGastoIndirectoCUPExcel()
    {
        $this->__load();
        return parent::getGastoIndirectoCUPExcel();
    }

    public function setGastoIndirectoCUCExcel($gastoIndirectoCUCExcel)
    {
        $this->__load();
        return parent::setGastoIndirectoCUCExcel($gastoIndirectoCUCExcel);
    }

    public function getGastoIndirectoCUCExcel()
    {
        $this->__load();
        return parent::getGastoIndirectoCUCExcel();
    }

    public function setGastoPresupuestoIndCUPExcel($gastoPresupuestoIndCUPExcel)
    {
        $this->__load();
        return parent::setGastoPresupuestoIndCUPExcel($gastoPresupuestoIndCUPExcel);
    }

    public function getGastoPresupuestoIndCUPExcel()
    {
        $this->__load();
        return parent::getGastoPresupuestoIndCUPExcel();
    }

    public function setGastoPresupuestoIndCUCExcel($gastoPresupuestoIndCUCExcel)
    {
        $this->__load();
        return parent::setGastoPresupuestoIndCUCExcel($gastoPresupuestoIndCUCExcel);
    }

    public function getGastoPresupuestoIndCUCExcel()
    {
        $this->__load();
        return parent::getGastoPresupuestoIndCUCExcel();
    }

    public function setGastoImprevistosCUPExcel($gastoImprevistosCUPExcel)
    {
        $this->__load();
        return parent::setGastoImprevistosCUPExcel($gastoImprevistosCUPExcel);
    }

    public function getGastoImprevistosCUPExcel()
    {
        $this->__load();
        return parent::getGastoImprevistosCUPExcel();
    }

    public function setGastoImprevistosCUCExcel($gastoImprevistosCUCExcel)
    {
        $this->__load();
        return parent::setGastoImprevistosCUCExcel($gastoImprevistosCUCExcel);
    }

    public function getGastoImprevistosCUCExcel()
    {
        $this->__load();
        return parent::getGastoImprevistosCUCExcel();
    }

    public function setGastoCostoTotalCUPExcel($gastoCostoTotalCUPExcel)
    {
        $this->__load();
        return parent::setGastoCostoTotalCUPExcel($gastoCostoTotalCUPExcel);
    }

    public function getGastoCostoTotalCUPExcel()
    {
        $this->__load();
        return parent::getGastoCostoTotalCUPExcel();
    }

    public function setGastoCostoTotalCUCExcel($gastoCostoTotalCUCExcel)
    {
        $this->__load();
        return parent::setGastoCostoTotalCUCExcel($gastoCostoTotalCUCExcel);
    }

    public function getGastoCostoTotalCUCExcel()
    {
        $this->__load();
        return parent::getGastoCostoTotalCUCExcel();
    }

    public function setGastoPorCientoUtilidadExcel($gastoPorCientoUtilidadExcel)
    {
        $this->__load();
        return parent::setGastoPorCientoUtilidadExcel($gastoPorCientoUtilidadExcel);
    }

    public function getGastoPorCientoUtilidadExcel()
    {
        $this->__load();
        return parent::getGastoPorCientoUtilidadExcel();
    }

    public function setGastoUtilidadCUPExcel($gastoUtilidadCUPExcel)
    {
        $this->__load();
        return parent::setGastoUtilidadCUPExcel($gastoUtilidadCUPExcel);
    }

    public function getGastoUtilidadCUPExcel()
    {
        $this->__load();
        return parent::getGastoUtilidadCUPExcel();
    }

    public function setGastoUtilidadCUCExcel($gastoUtilidadCUCExcel)
    {
        $this->__load();
        return parent::setGastoUtilidadCUCExcel($gastoUtilidadCUCExcel);
    }

    public function getGastoUtilidadCUCExcel()
    {
        $this->__load();
        return parent::getGastoUtilidadCUCExcel();
    }

    public function setGastoPrecioServConstCUPExcel($gastoPrecioServConstCUPExcel)
    {
        $this->__load();
        return parent::setGastoPrecioServConstCUPExcel($gastoPrecioServConstCUPExcel);
    }

    public function getGastoPrecioServConstCUPExcel()
    {
        $this->__load();
        return parent::getGastoPrecioServConstCUPExcel();
    }

    public function setGastoPrecioServConstCUCExcel($gastoPrecioServConstCUCExcel)
    {
        $this->__load();
        return parent::setGastoPrecioServConstCUCExcel($gastoPrecioServConstCUCExcel);
    }

    public function getGastoPrecioServConstCUCExcel()
    {
        $this->__load();
        return parent::getGastoPrecioServConstCUCExcel();
    }

    public function setGastoPagoTributosCUPExcel($gastoPagoTributosCUPExcel)
    {
        $this->__load();
        return parent::setGastoPagoTributosCUPExcel($gastoPagoTributosCUPExcel);
    }

    public function getGastoPagoTributosCUPExcel()
    {
        $this->__load();
        return parent::getGastoPagoTributosCUPExcel();
    }

    public function setGastoPagoTributosCUCExcel($gastoPagoTributosCUCExcel)
    {
        $this->__load();
        return parent::setGastoPagoTributosCUCExcel($gastoPagoTributosCUCExcel);
    }

    public function getGastoPagoTributosCUCExcel()
    {
        $this->__load();
        return parent::getGastoPagoTributosCUCExcel();
    }

    public function setGastoPrecioMOCUPExcel($gastoPrecioMOCUPExcel)
    {
        $this->__load();
        return parent::setGastoPrecioMOCUPExcel($gastoPrecioMOCUPExcel);
    }

    public function getGastoPrecioMOCUPExcel()
    {
        $this->__load();
        return parent::getGastoPrecioMOCUPExcel();
    }

    public function setGastoPrecioMOCUCExcel($gastoPrecioMOCUCExcel)
    {
        $this->__load();
        return parent::setGastoPrecioMOCUCExcel($gastoPrecioMOCUCExcel);
    }

    public function getGastoPrecioMOCUCExcel()
    {
        $this->__load();
        return parent::getGastoPrecioMOCUCExcel();
    }

    public function setGastoPrecioMaterialesCUPExcel($gastoPrecioMaterialesCUPExcel)
    {
        $this->__load();
        return parent::setGastoPrecioMaterialesCUPExcel($gastoPrecioMaterialesCUPExcel);
    }

    public function getGastoPrecioMaterialesCUPExcel()
    {
        $this->__load();
        return parent::getGastoPrecioMaterialesCUPExcel();
    }

    public function setGastoPrecioMaterialesCUCExcel($gastoPrecioMaterialesCUCExcel)
    {
        $this->__load();
        return parent::setGastoPrecioMaterialesCUCExcel($gastoPrecioMaterialesCUCExcel);
    }

    public function getGastoPrecioMaterialesCUCExcel()
    {
        $this->__load();
        return parent::getGastoPrecioMaterialesCUCExcel();
    }

    public function setGastoPrecioTotalServConstCUPExcel($gastoPrecioTotalServConstCUPExcel)
    {
        $this->__load();
        return parent::setGastoPrecioTotalServConstCUPExcel($gastoPrecioTotalServConstCUPExcel);
    }

    public function getGastoPrecioTotalServConstCUPExcel()
    {
        $this->__load();
        return parent::getGastoPrecioTotalServConstCUPExcel();
    }

    public function setGastoPrecioTotalServConstCUCExcel($gastoPrecioTotalServConstCUCExcel)
    {
        $this->__load();
        return parent::setGastoPrecioTotalServConstCUCExcel($gastoPrecioTotalServConstCUCExcel);
    }

    public function getGastoPrecioTotalServConstCUCExcel()
    {
        $this->__load();
        return parent::getGastoPrecioTotalServConstCUCExcel();
    }

    public function setIdContrato(\CCC\OfertasBundle\Entity\Contratos $idContrato = NULL)
    {
        $this->__load();
        return parent::setIdContrato($idContrato);
    }

    public function getIdContrato()
    {
        $this->__load();
        return parent::getIdContrato();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'facturado', 'objeto', 'desde', 'hasta', 'gastoResuemenPresupuestoCUPExcel', 'gastoResuemenPresupuestoCUCExcel', 'gastoDirectoCUPExcel', 'gastoDirectoCUCExcel', 'gastoGeneralCUPExcel', 'gastoGeneralCUCExcel', 'gastoIndirectoCUPExcel', 'gastoIndirectoCUCExcel', 'gastoPresupuestoIndCUPExcel', 'gastoPresupuestoIndCUCExcel', 'gastoImprevistosCUPExcel', 'gastoImprevistosCUCExcel', 'gastoCostoTotalCUPExcel', 'gastoCostoTotalCUCExcel', 'gastoPorCientoUtilidadExcel', 'gastoUtilidadCUPExcel', 'gastoUtilidadCUCExcel', 'gastoPrecioServConstCUPExcel', 'gastoPrecioServConstCUCExcel', 'gastoPagoTributosCUPExcel', 'gastoPagoTributosCUCExcel', 'gastoPrecioMOCUPExcel', 'gastoPrecioMOCUCExcel', 'gastoPrecioMaterialesCUPExcel', 'gastoPrecioMaterialesCUCExcel', 'gastoPrecioTotalServConstCUPExcel', 'gastoPrecioTotalServConstCUCExcel', 'idContrato');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}